#
# Copyright (C) 2024 Intel Corporation.
#
# SPDX-License-Identifier: BSD-3-Clause
#

version: '3.7'
services:
  camera-simulator:
    container_name: camera-simulator
    image: aler9/rtsp-simple-server
    networks:
      edgex-network: { }
    ports:
      - "8554:8554"
  camera-simulator0:
    build:
      context: .
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator0
    networks:
      edgex-network: { }
    entrypoint: ffmpeg
    command: "
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/coca-cola-4465029-1920-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport
        tcp
        rtsp://camera-simulator:8554/camera_0
        "
    depends_on:
      - camera-simulator
    volumes:
      - ../../performance-tools/sample-media:/home/pipeline-server/sample-media
  ovms-server:
    image: ovms-server:dev
    container_name: ovms-server0
    networks:
      edgex-network: { }
    restart: always
    ports:
      - '9001:9001'
      - '9002:9002'
    volumes:
      - ../../models:/models
    environment:
      - TARGET_DEVICE=CPU
      - PLATFORM="core"
      - server_cl_cache_dir=/home/pipeline-server/.cl-cache
  pipeline-grpc-go:
    command: /as-pipeline-grpc-go -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res -s
    depends_on:
      - edgex-security-bootstrapper
      - ovms-server
      - camera-simulator0
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      API_GATEWAY_HOST: edgex-kong
      API_GATEWAY_STATUS_PORT: '8100'
      EDGEX_SECURITY_SECRET_STORE: "true"
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      REGISTRY_HOST: edgex-core-consul
      SECRETSTORE_HOST: edgex-vault
      SECRETSTORE_PORT: '8200'
      SERVICE_HOST: pipeline-grpc-go
      SPIFFE_ENDPOINTSOCKET: /tmp/edgex/secrets/spiffe/public/api.sock
      SPIFFE_TRUSTBUNDLE_PATH: /tmp/edgex/secrets/spiffe/trust/bundle
      SPIFFE_TRUSTDOMAIN: edgexfoundry.org
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: '54321'
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: '6379'
      STAGEGATE_DATABASE_READYPORT: '6379'
      STAGEGATE_KONGDB_HOST: edgex-kong-db
      STAGEGATE_KONGDB_PORT: '5432'
      STAGEGATE_KONGDB_READYPORT: '54325'
      STAGEGATE_READY_TORUNPORT: '54329'
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: '8500'
      STAGEGATE_REGISTRY_READYPORT: '54324'
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: '54322'
      STAGEGATE_WAITFOR_TIMEOUT: 60s
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_AUTHMODE: usernamepassword
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_SECRETNAME: redisdb
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-redis
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-redis
      WRITABLE_LOGLEVEL: DEBUG
      APPLICATIONSETTINGS_OVMSGRPCHOST: ovms-server0
      APPLICATIONSETTINGS_OVMSGRPCPORT: 9001
      RENDER_MODE: 0 #RENDER_MODE=1 will work only after running xhost +local:docker
      DISPLAY: $DISPLAY
    image: aicsd/as-pipeline-grpc-go:0.0.0-dev
    networks:
      edgex-network: {}
    volumes:
      - ${HOME}/data/gateway-files:/tmp/files
      - edgex-init:/edgex-init:z
      - ~/.Xauthority:/home/dlstreamer/.Xauthority
      - /tmp/.X11-unix
      - /tmp/edgex/secrets/app-pipeline-grpc-go:/tmp/edgex/secrets/app-pipeline-grpc-go:ro,z
