########################################################################
 # Copyright (c) Intel Corporation 2023
 # SPDX-License-Identifier: BSD-3-Clause
########################################################################

version: '3.7'
networks:
  edgex-network:
    driver: bridge
services:
  pipeline-sim:
    command: /as-pipeline-sim -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res -s
    depends_on:
      - security-bootstrapper
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: pipeline-sim
      SPIFFE_ENDPOINTSOCKET: /tmp/edgex/secrets/spiffe/public/api.sock
      SPIFFE_TRUSTBUNDLE_PATH: /tmp/edgex/secrets/spiffe/trust/bundle
      SPIFFE_TRUSTDOMAIN: edgexfoundry.org
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_AUTHMODE: usernamepassword
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_SECRETNAME: redisdb
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-redis
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-redis
      WRITABLE_LOGLEVEL: DEBUG
    image: aicsd/as-pipeline-sim:0.0.0-dev
    networks:
      edgex-network: {}
    ports:
      - 10107:59789/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - ${HOME}/data/gateway-files:/tmp/files
      - ./models:/models
      - edgex-init:/edgex-init:z
      - /tmp/edgex/secrets/app-pipeline-sim:/tmp/edgex/secrets/app-pipeline-sim:ro,z
